name: cienv
dependencies:
    - python>=3.9
    - pip
    - pre-commit
    - pytest
    - numpy
    - awkward >= 2.5.0
    - furo
    - breathe
    - sphinx
    - conda-forge::doxygen>=1.10.0
    - pip:
      - sphinx_copybutton
      - sphinxcontrib-bibtex
