name: cienv
dependencies:
    - python>=3.9
    - pytest
    - sphinx
    - conda-forge::doxygen>=1.10.0
    - pip
    - pip:
      - numpy
      - pytest
      - sphinx
      - furo
      - sphinx_copybutton
      - sphinxcontrib-bibtex
      - sphinxcontrib-applehelp
      - sphinxcontrib-htmlhelp
      - breathe
      - pre-commit
