from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"
pre_package_bump_hooks = []
post_package_bump_hooks = []

pre_bump_hooks = [
    "echo 'bumping version from {{latest}} to {{version}}'"
]

post_bump_hooks = [
    "git push",
    "echo 'bump done with chore commit for notes appended to changelog'",
]

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "CLEO"
owner = "yoctoyotta1024"
authors = [{ username = "yoctoyotta1024", signature = "Clara Bayley" }]

[bump_profiles]

[packages]
