# ----- CLEO -----
# File: pybind_config.yaml
# Project: config
# Created Date: Friday 6th June 2025
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for example of using CLEO's python bindings.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's cleopy module (see Python script "create_initsuperdropsbinary_script.py" for example of usage).
# Likewise the "grid_filename" can be made using cleopy (see "create_gbxboundariesbinary_script.py").
#

### Kokkos Initialization Parameters ###
kokkos_settings:
  num_threads : 128                                    # number of threads for host parallel backend
  device_id :  0                                       # device to use for device parallel backend
  map_device_id_by : random                            # select device for execution, either "mpi_rank" or "random".

### SDM Runtime Parameters ###
domain:
  nspacedims : 2                                          # no. of spatial dimensions to model
  ngbxs : 9                                               # total number of Gbxs
  maxnsupers: 36                                          # maximum number of SDs

timesteps:
  CONDTSTEP : 3                                           # time between SD condensation [s]
  COLLTSTEP : 3                                           # time between SD collision [s]
  MOTIONTSTEP : 3                                         # time between SDM motion [s]
  COUPLTSTEP : 3600                                       # time between dynamic couplings [s]
  OBSTSTEP : 180                                          # time between SDM observations [s]
  T_END : 7200                                            # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ./libs/cleoconstants.hpp   # name of file for values of physical constants
  grid_filename : ./build/share/pybind_dimlessGBxboundaries.dat   # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                        # type of initialisation of super-droplets
  initsupers_filename : ./build/share/pybind_dimlessSDsinit.dat   # binary filename for initialisation of SDs
  initnsupers: 24

### Output Parameters ###
outputdata:
  setup_filename : ./build/bin/pybind_setup.txt                   # .txt filename to copy configuration to
  zarrbasedir : ./build/bin/pybind_sol.zarr                       # zarr store base directory
  maxchunk : 2500000                                      # maximum no. of elements in chunks of zarr store array

### CLEO Python Bindings Parameters ###
python_bindings:
  enable_terminal_velocity : true                                   # true enables terminal velocity in superdroplet motion
  enable_condensation : false                                       # true enables condensation in microphysics
  enable_collisions : false                                         # true enables collisions in microphysics
  enable_observers:                                                 # true for the following set enables various observers
    time : true
    gbxindex : true                                                 # currently only true is allowed for gbxindex observer
    totnsupers : true
    massmoms : true
    rainmassmoms : true
    gridboxes : true
    superdrops : true
    precip : true
