# ----- CLEO -----
# File: shima2009_config.yaml
# Project: config
# Created Date: Wednesday 17th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Friday 14th June 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for example of collisions in CLEO SDM 0-D box model.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims: 0                                                 # no. of spatial dimensions to model
  ngbxs: 1                                                      # total number of Gbxs
  maxnsupers: 8192                                              # maximum number of SDs

timesteps:
  CONDTSTEP: 200                                                # time between SD condensation [s]
  COLLTSTEP: 0.1                                                # time between SD collision [s]
  MOTIONTSTEP: 200                                              # time between SDM motion [s]
  COUPLTSTEP: 2000                                              # time between dynamic couplings [s]
  OBSTSTEP: 200                                                 # time between SDM observations [s]
  T_END: 3800                                                   # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename: ../libs/cleoconstants.hpp                 # name of file for values of physical constants
  grid_filename: ./share/shima2009_dimlessGBxboundaries.dat     # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename: /home/m/m300950/CLEO/build_colls0D//share/shima2009_dimlessSDsinit_2.dat # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename: ./bin/shima2009_setup.txt                     # .txt filename to copy configuration to
  stats_filename: ./bin/shima2009_stats.txt                     # .txt file to output runtime statistics to
  zarrbasedir: ./bin/shima2009_sol.zarr                         # zarr store base directory
  maxchunk: 2500000                                             # maximum no. of elements in chunks of zarr store array
