name: publish cleopy to PyPI (if CHANGELOG.md updated)

on:
  workflow_run:
    workflows: ["cocogitto (and release)"]
    types:
      - completed

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    # Only release new version when merging into `origin/main`.` (same as cocogitto.yml release job)
    if: "github.ref == 'refs/heads/main'"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: astral-sh/setup-uv@v3
      # Only release new version of cleopy when CHANGELOG.md changes (e.g. by cocogitto.yml)
      - name: check for difference in changelog
        id: check_changelog
        run: |
          git diff --name-only ${{ github.sha }}^ ${{ github.sha }} > diff_files.txt
          cat diff_files.txt
          if grep -qE '^CHANGELOG\.md$' diff_files.txt; then
            echo "is_diff=true"  >> "$GITHUB_OUTPUT"
          else
            echo "is_diff=false" >> "$GITHUB_OUTPUT"
          fi
          echo "changelog difference ${{ steps.check_changelog.outputs.is_diff }}"
      - name: publish cleopy
        if: ${{ steps.check_changelog.outputs.is_diff }} == "true"
        run: |
          echo "difference in CHANGELOG.md detected, publishing cleopy"
          uv build
          ls dist/
          uv publish --trusted-publishing always
